# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-08 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='pdu1',
        ),
        migrations.RemoveField(
            model_name='system',
            name='pdu2',
        ),
    ]
