# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-08 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_auto_20190108_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='pdu1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='pdu2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
