# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-01 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_auto_20190108_0542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemrack',
            unique_together=set([('name', 'site')]),
        ),
    ]
