# Generated by Django 2.0.13 on 2019-02-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_auto_20190204_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='is_dhcp_server',
        ),
        migrations.RemoveField(
            model_name='system',
            name='is_dns_server',
        ),
        migrations.RemoveField(
            model_name='system',
            name='is_nagios_server',
        ),
        migrations.RemoveField(
            model_name='system',
            name='is_puppet_server',
        ),
        migrations.RemoveField(
            model_name='system',
            name='is_switch',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pager_type',
            field=models.CharField(blank=True, choices=[('epager', 'epager'), ('sms', 'sms')], max_length=255, null=True),
        ),
    ]
