# Generated by Django 2.0.13 on 2019-02-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_auto_20190219_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='current_revision',
            field=models.IntegerField(default=0),
        ),
    ]
