# Generated by Django 2.0.13 on 2019-03-15 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_system_current_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.OperatingSystem'),
        ),
    ]
